# Generated by Django 5.2.9 on 2025-12-03 02:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('personal', 'Personal')], max_length=20)),
                ('icono', models.CharField(blank=True, help_text='Clase de Font Awesome o símbolo', max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='Sofía Lagos', max_length=100)),
                ('apodo', models.CharField(default='tori', max_length=50)),
                ('titulo', models.CharField(default='desarrolladora full stack python · artista visual', max_length=200)),
                ('descripcion', models.TextField()),
                ('github_url', models.URLField(default='https://github.com/too0oori')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(default='sofia.lagos.cesped@gmail.com', max_length=254)),
                ('ilustracion_contacto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(help_text='Imagen principal del proyecto', upload_to='proyectos/')),
                ('url_codigo', models.URLField(help_text='Link a GitHub', validators=[django.core.validators.URLValidator()])),
                ('url_demo', models.URLField(blank=True, help_text='Link al sitio desplegado (opcional)', null=True)),
                ('tecnologias', models.CharField(help_text='Separadas por coma: Python, Django, Bootstrap', max_length=300)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en la sección principal')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/capturas/')),
                ('descripcion', models.CharField(help_text='Descripción de la captura', max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='main.proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyectos',
                'ordering': ['orden'],
            },
        ),
    ]
